from enum import Enum

class Instruction(Enum):
    PUSH = 'push'
    POP = 'pop'
    ADD = 'add'
    SUB = 'sub'
    MUL = 'mul'
    DIV = 'div'
    MOD = 'mod'
    UMINUS = 'uminus'
    CONCAT = 'concat'
    AND = 'and'
    OR = 'or'
    NOT = 'not'
    GT = 'gt'
    LT = 'lt'
    EQ = 'eq'
    READ = 'read'
    PRINT = 'print'
    SAVE = 'save'
    LOAD = 'load'
    LABEL = 'label'
    JMP = 'jmp'
    FJMP = 'fjmp'
    FWRITE = 'fwrite'
